# Generated by Django 4.2.1 on 2023-06-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0005_alter_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='authors',
        ),
    ]
