# Generated by Django 4.2.1 on 2023-06-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0006_rename_author_quote_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created',
        ),
    ]
