# Generated by Django 4.2.1 on 2023-06-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0009_alter_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='authors',
        ),
        migrations.AddField(
            model_name='quote',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quoteapp.author'),
            preserve_default=False,
        ),
    ]
