# Generated by Django 4.2.1 on 2023-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0010_remove_quote_authors_quote_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='authors',
        ),
        migrations.AddField(
            model_name='quote',
            name='authors',
            field=models.ManyToManyField(to='quoteapp.author'),
        ),
    ]
